[package]
name = "traffic-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winit = { version = "0.30", features = ["rwh_05"]}
pixels = "0.13.0"
rand = "0.8.5"
ndarray = "0.15"
rayon = "1.5"
